trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Internal Access Program WW Inside Sales_Subscription Cont(f0efe35e-b5a6-42ef-9a7a-e11fa99a1f8f)'
    subscriptionId: 'f0efe35e-b5a6-42ef-9a7a-e11fa99a1f8f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'koheisaitolearn'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'templates/azuredeploy.json'
    csmParametersFile: 'parameters/azuredeploy.json'
    deploymentMode: 'Incremental'