trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Internal Access Program WW Inside Sales_Subscription Cont(f0efe35e-b5a6-42ef-9a7a-e11fa99a1f8f)'
    subscriptionId: 'f0efe35e-b5a6-42ef-9a7a-e11fa99a1f8f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'VstsRG-pipeline-dotnet-11c4'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'templates/resourceGroup.json'
    csmParametersFile: 'parameters/resourceGroup.json'
    overrideParameters: '-resourceName "hogehoge"'
    deploymentMode: 'Incremental'